[mgr]
prepend_keymap = [
  # 进入终端
  { on = "!", run = 'shell "fish" --block' },

  # 插件功能
  ## compress: 压缩文档
  { on = [ "c", "a" ], run = "plugin compress" },

  ## simple-mtpfs: mtp挂载
  { on = [ "M", "m" ], run = "plugin simple-mtpfs -- select-then-mount --jump", desc = "选择设备挂载并跳转" },
  { on = [ "M", "r" ], run = "plugin simple-mtpfs -- remount-current-cwd-device", desc = "重新挂载当前工作目录的设备" },
  { on = [ "M", "u" ], run = "plugin simple-mtpfs -- select-then-unmount", desc = "选择设备并卸载" },
  { on = [ "M", "g" ], run = "plugin simple-mtpfs -- jump-to-device", desc = "选择设备并跳转到挂载点" },
  { on = [ "`", "`" ], run = "plugin simple-mtpfs -- jump-back-prev-cwd", desc = "回到跳转到此设备挂载点前的位置" },
  ## relative-motions: vim的相对motions
  { on = "e", run = "plugin relative-motions", desc = "跳转到相对行"},

  # 目录跳转
  ## 文档目录
  { on = [ "g", "d", "d" ], run = "cd /home/lh/Downloads" },
  { on = [ "g", "d", "p", "p" ], run = "cd /home/lh/Pictures" },
  { on = [ "g", "d", "p", "g" ], run = "cd /home/lh/Pictures/Gallery" },
  { on = [ "g", "d", "p", "w" ], run = "cd /home/lh/Pictures/Wallpapers" },
  { on = [ "g", "d", "p", "s" ], run = "cd /home/lh/Pictures/Screenshots" },
  { on = [ "g", "d", "v", "v" ], run = "cd /home/lh/Videos" },
  { on = [ "g", "d", "v", "r" ], run = "cd /home/lh/Videos/Recordings" },
  { on = [ "g", "d", "v", "a" ], run = "cd /home/lh/Videos/Anime" },
  { on = [ "g", "d", "m" ], run = "cd /home/lh/Music" },
  { on = [ "g", "d", "o" ], run = "cd /home/lh/Public/share/obsidian" },
  { on = [ "g", "d", "g", "g" ], run = "cd /home/lh/git" },
  { on = [ "g", "d", "g", "d" ], run = "cd /home/lh/git/dotfile" },
  { on = [ "g", "d", "g", "c" ], run = "cd /home/lh/git/caelestia" },
  { on = [ "g", "d", "P" ], run = "cd /home/lh/Program" },
  { on = [ "g", "d", "s" ], run = "cd /home/lh/Script" },
  ## config目录
  { on = [ "g", "c", "c" ], run = "cd /home/lh/.config" },
  { on = [ "g", "c", "y" ], run = "cd /home/lh/.config/yazi" },
  { on = [ "g", "c", "g" ], run = "cd /home/lh/.config/go-musicfox" },
  { on = [ "g", "c", "r" ], run = "cd /home/lh/.config/rmpc" },
  { on = [ "g", "c", "k" ], run = "cd /home/lh/.config/kitty" },
  { on = [ "g", "c", "h" ], run = "cd /home/lh/.config/hypr" },
  { on = [ "g", "c", "n" ], run = "cd /home/lh/.config/nvim" },
  { on = [ "g", "c", "f" ], run = "cd /home/lh/.config/fish" },
  ## cache目录
  { on = [ "g", "C", "C" ], run = "cd /home/lh/.cache" },
  { on = [ "g", "C", "g" ], run = "cd /home/lh/.cache/go-musicfox" },
  ## local目录
  { on = [ "g", "l", "s", "s" ], run = "cd /home/lh/.local/share" },
  { on = [ "g", "l", "s", "a" ], run = "cd /home/lh/.local/share/applications" },
  { on = [ "g", "l", "t" ], run = "cd /home/lh/.local/state" },
  ## share目录
  { on = [ "g", "s", "s" ], run = "cd /usr/share" },
  ## 程序目录
  { on = [ "g", "a", "s", "w" ], run = "cd /home/lh/.steam/steam/steamapps/workshop/content/431960", desc = "WallpaperEngineData for steam" },
  { on = [ "g", "a", "w", "d" ], run = "cd /home/lh/Documents/xwechat_files/wxid_wq6oqrz4aywl22_7cad/msg/file", desc = "微信下载文件目录" },
  { on = [ "g", "a", "w", "w" ], run = "cd /home/lh/.wine/drive_c/users", desc = "wine用户目录" },

]

[input]
prepend_keymap = [
  # 退出shell模式
  { on = "<Esc>", run = "close", desc = "Cancel input" },
]
